mobile_base_controller:
  enable_odom_tf: true
  odom_frame_id: odom
  publish_cmd: true
  angular:
    z: {has_acceleration_limits: true, has_jerk_limits: true, has_velocity_limits: true,
      max_acceleration: 2.5, max_jerk: 5.0, max_velocity: 25.0}
  base_frame_id: base_link
  cmd_vel_timeout: 1.15 # needed to be higher due to some networks lags, was 0.25
  left_wheel: wheel_0_joint
  linear:
    x: {has_acceleration_limits: true, has_jerk_limits: true, has_velocity_limits: true,
      max_acceleration: 1.0, max_jerk: 5.0, max_velocity: 25.0, min_acceleration: -1.0,
      min_velocity: -25.0}
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  publish_rate: 25.0 # 100.0
  right_wheel: wheel_1_joint
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  type: diff_drive_controller/DiffDriveController
  wheel_radius: 0.03315
  wheel_radius_multiplier: 1.0
  wheel_separation: 0.1655
  wheel_separation_multiplier: 1.0

